### ISSUE TITLE
need help for using this lib on a ESP8266

### ISSUE THREAD

**Issue by jpduhen** [CelliesProjects/moonPhase#2]
Hello Cellie,
Love to use your excellent lib on a ESP8266, but have little experience in how to change the code to get it running on the older ESP8266. Could you point me in the right direction?

**Comment by CelliesProjects** [comment]
Hi @jpduhen No idea. Can you be more specific about your issues?

**Comment by CelliesProjects** [comment]
Just saw there is a fork that targets avr. Might be more compatible with esp8266.

https://github.com/steve-sienk/moonPhaser-avr

**Comment by jpduhen** [comment]
Problem was not your routine, but the call to the **getLocalTime()** which is valid for ESP32's WiFi.h, but not for ESP8266's ESP8266WiFi.h Have found a way to use it on a ESP8266 by adding this:


> #ifdef ESP8266
> 
> void getLocalTime()
> {
>   time_t rawtime;
>   struct tm * timeinfo;
> 
>   time (&rawtime);
>   timeinfo = localtime (&rawtime);
> 
>   strftime (buffer,80," %d %B %Y %H:%M:%S ",timeinfo);
>   //struct tm timeinfo;
>   //time_t now = time(nullptr);
>   Serial.println(buffer);
>   //Serial.print(ctime(&now));
>   //Serial.print(&timeinfo, " %d %B %Y %H:%M:%S ");
> }
> 
> #endif


Feel free to add this to your SNTP example to make it ESP8266 friendly ;-)

**Comment by jpduhen** [comment]
Getting stuck on definitions:
Your library ESP32 example file for SNTP uses this: 

> struct tm timeinfo = {0};

In the ESP8266 sketch I found  this struct is different:   

> struct tm * timeinfo;

I'm lost on how to to adapt this, one is a pointer the other a char *. Is it possible to "convert" the char * to your pointer-type?

**Comment by jpduhen** [comment]
Yes got it running with some modifications:
```
void loop() 
{
  getLocalTime();
  
  #ifdef ESP8266
    Serial.print((String)timeinfo->tm_mday + " - ");
    Serial.print((String)(1 + timeinfo->tm_mon) + " ");
    Serial.print((String)(1900 + timeinfo->tm_year) + " - ");
    Serial.println((String)timeinfo->tm_hour);
    moonData_t moon = moonPhase.getPhase((timeinfo->tm_year + 1900), (timeinfo->tm_mon + 1), timeinfo->tm_mday, timeinfo->tm_hour);
  #else
    Serial.print( asctime( &timeinfo ) );
    moonData_t moon = moonPhase.getPhase();
  #endif
  
  Serial.print( "Moon phase angle: " );
  Serial.print( moon.angle );                       // angle is a integer between 0-360
  Serial.print( " degrees. Moon surface lit: " );
  Serial.printf( "%f%%\n", moon.percentLit * 100 ); // percentLit is a real between 0-1
  Serial.println();
  
  delay(1000);
}
```

And a ESP8266 specific version of `getLocalTime()`:

```
#ifdef ESP8266
void getLocalTime()
{
  time (&rawtime);
  timeinfo = localtime (&rawtime);
}
#endif

```

**Comment by CelliesProjects** [comment]
@jpduhen That would be the RTOS version of esp8266?
